/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:2c31e03c-28fb-45e2-b12b-8171799903cc",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_MMImrRwew",
    "aws_user_pools_web_client_id": "rpmbf5jhjscr79200ni4grsnn",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://he7ophgghvfq5fz7zne6kjbugu.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-of5r7d3aivepxgs356z4l22oha"
};


export default awsmobile;
